In [1]:
import pandas as pd

In [2]:
plants = 'plants.csv'
plants_2010 = 'List_of_plants_for_all_fuels_United_States_all_sectors_2010.csv'
plants_df = pd.read_csv(plants)
plants2010_df = pd.read_csv(plants_2010)
plants2011_df = pd.read_csv('List_of_plants_for_all_fuels_United_States_all_sectors2011.csv')

In [3]:
plants_dfs = plants_df.loc[plants_df['year']==2010]
plants_dfs = plants_dfs.rename(columns={'plant_id':'Plant Code','plant_name_cap':'Plant Name'})
plants_dfs.head()

,year,Plant Code,plant_name_gen,operator_name_gen,operator_id_gen,net_generation_mwh,Plant Name,operator_name_cap,operator_id_cap,state,nameplate_mw,summer_mw,capacity_mwh,capacity_utilization,minimum_year
50038,2010.0,56545.0,Seneca City of,City of Seneca,16921.0,1042.0,Seneca City of,City of Seneca,16921.0,SC,10.0,9.0,78840.0,0.013217,2004.0
50039,2010.0,56550.0,Huntersville Delivery No 2,North Carolina Mun Power Agny #1,13630.0,17.0,Huntersville Delivery No 2,North Carolina Mun Power Agny #1,13630.0,NC,2.2,2.0,17520.0,0.000970,2007.0
50040,2010.0,56546.0,Cornelius Delivery No 1,North Carolina Mun Power Agny #1,13630.0,8.0,Cornelius Delivery No 1,North Carolina Mun Power Agny #1,13630.0,NC,2.2,2.0,17520.0,0.000457,2007.0
50041,2010.0,56547.0,Bostic Delivery No 1,North Carolina Mun Power Agny #1,13630.0,-11.0,Bostic Delivery No 1,North Carolina Mun Power Agny #1,13630.0,NC,1.0,1.0,8760.0,-0.001256,2007.0
50042,2010.0,56548.0,Drexel Operations Center,North Carolina Mun Power Agny #1,13630.0,6.0,Drexel Operations Center,North Carolina Mun Power Agny #1,13630.0,NC,2.2,2.0,17520.0,0.000342,2007.0

In [4]:
plants2010_df = plants2010_df.loc[plants2010_df['State'] == 'CA']

In [5]:
merged_df = pd.merge(plants_dfs,plants2010_df,on=['Plant Code','Plant Name'])

In [6]:
merged_df=merged_df.drop(labels=['operator_name_cap','operator_name_gen','plant_name_gen','operator_id_cap'],axis=1)
sun_power_CA = merged_df.loc[merged_df['Fuel Types'] == "SUN"]
sun_power_CA['state'].value_counts()

CA    29
Name: state, dtype: int64

In [7]:
merged_df['state'].value_counts()

CA    635
Name: state, dtype: int64

In [8]:
plants2011_df = plants2011_df.loc[plants2011_df['State']=='CA']

In [9]:
plants_2011_df = plants_df.loc[plants_df['year']==2011]
plants_2011_df = plants_2011_df.rename(columns={'plant_id':'Plant Code','plant_name_cap':'Plant Name'})
plants_2011_df = plants_2011_df.loc[plants_2011_df['state']=='CA']

In [10]:
new_merge = pd.merge(plants_2011_df,plants2011_df,on=['Plant Code','Plant Name'])

In [11]:
new_merge.head()

,year,Plant Code,plant_name_gen,operator_name_gen,operator_id_gen,net_generation_mwh,Plant Name,operator_name_cap,operator_id_cap,state,nameplate_mw,summer_mw,capacity_mwh,capacity_utilization,minimum_year,State,Sector Name,Prime Movers,Fuel Types
0,2011.0,56909.0,Gap Pacific Distribution Center,MMA GDC Power LP,56113.0,1974.06,Gap Pacific Distribution Center,MMA GDC Power LP,56113.0,CA,1.2,1.2,10512.0,0.187791,2008.0,CA,Commercial non-cogen,PV,SUN
1,2011.0,56914.0,Orange Grove Peaking Facility,Orange Grove Energy LP,56127.0,38975.00,Orange Grove Peaking Facility,Orange Grove Energy LP,56127.0,CA,118.0,99.2,868992.0,0.044851,2010.0,CA,Electric utility non-cogen,GT,NG
2,2011.0,56943.0,Ausra Kimberlina Solar Generation,Ausra CA I LLC,56207.0,4.85,Ausra Kimberlina Solar Generation,Ausra CA I LLC,56207.0,CA,5.0,3.5,30660.0,0.000158,NaN,CA,Electric utility non-cogen,ST,SUN
3,2011.0,56813.0,CSU Fresno Solar Project,MMA Fresno Power LP,56028.0,981.09,CSU Fresno Solar Project,MMA Fresno Power LP,56028.0,CA,1.0,1.0,8760.0,0.111997,2007.0,CA,Electric utility non-cogen,PV,SUN
4,2011.0,56814.0,ELACC Photovoltaic Power Facility,MMA LA Power LP,56027.0,1672.11,ELACC Photovoltaic Power Facility,MMA LA Power LP,56027.0,CA,1.0,0.8,7008.0,0.238600,2008.0,CA,Electric utility non-cogen,PV,SUN

In [12]:
plants_2011_df['state'].value_counts()

CA    839
Name: state, dtype: int64

In [13]:
plants_dfs['year'].value_counts()

2010.0    5894
Name: year, dtype: int64

In [14]:
plants_total = pd.read_csv(plants)
plants_total

,year,plant_id,plant_name_gen,operator_name_gen,operator_id_gen,net_generation_mwh,plant_name_cap,operator_name_cap,operator_id_cap,state,nameplate_mw,summer_mw,capacity_mwh,capacity_utilization,minimum_year
0,2001.0,2.0,Bankhead Dam,Alabama Power Co,195.0,234987.000,Bankhead Dam,Alabama Power Co,195.0,AL,45.0,56.0,490560.0,0.479018,1963.0
1,2001.0,50573.0,CID Gas Recovery,WM Illinois Renewable Energy LLC,54843.0,39158.001,CID Gas Recovery,Bio-Energy Partners,1687.0,IL,6.0,5.8,50808.0,0.770705,1989.0
2,2001.0,50572.0,CSL Gas Recovery,WM Renewable Energy LLC,54842.0,69691.000,CSL Gas Recovery,Bio-Energy Partners,1687.0,FL,11.2,10.9,95484.0,0.729871,1989.0
3,2001.0,50571.0,Altamont Gas Recovery,WM Renewable Energy LLC,54842.0,38814.000,Altamont Gas Recovery,Bio-Energy Partners,1687.0,CA,6.0,5.8,50808.0,0.763935,1969.0
4,2001.0,50570.0,Chestnut Ridge Gas Recovery,WM Renewable Energy LLC,54842.0,23660.002,Chestnut Ridge Gas Recovery,Bio-Energy Partners,1687.0,TN,3.2,3.2,28032.0,0.844035,1992.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90358,2015.0,55086.0,Gregory Power Facility,Gregory Power Partners LP,7667.0,2663022.000,Gregory Power Facility,Gregory Power Partners LP,7667.0,TX,432.0,366.0,3206160.0,0.830595,2000.0
90359,2015.0,55087.0,Zeeland Generating Station,Consumers Energy Co,4254.0,3471259.000,Zeeland Generating Station,Consumers Energy Co,4254.0,MI,968.2,843.0,7384680.0,0.470062,2001.0
90360,2015.0,55088.0,Dearborn Industrial Generation,Dearborn Industrial Gen Inc,4945.0,3501598.020,Dearborn Industrial Generation,Dearborn Industrial Gen Inc,4945.0,MI,760.0,741.6,6496416.0,0.539005,1999.0
90361,2015.0,55074.0,Lakeview Gas Recovery,WM Renewable Energy LLC,54842.0,44519.000,Lakeview Gas Recovery,WM Renewable Energy LLC,54842.0,PA,6.0,6.0,52560.0,0.847013,1997.0
90362,2015.0,60571.0,NaN,NaN,NaN,NaN,North City Cogeneration Facility,City of San Diego,16764.0,CA,1.6,1.4,12264.0,NaN,2013.0

In [15]:
plants_total['year'].value_counts()

2015.0    7601
2014.0    7240
2013.0    6892
2012.0    6587
2011.0    6111
2008.0    5958
2010.0    5894
2007.0    5761
2009.0    5735
2006.0    5625
2005.0    5514
2004.0    5441
2003.0    5389
2002.0    5321
2001.0    5294
Name: year, dtype: int64

In [21]:
plants_total_CA = plants_total.loc[plants_total['state'] == 'CA']
plants_total_CA['year'].value_counts()

2015.0    1200
2014.0    1127
2013.0    1025
2012.0     938
2011.0     839
2008.0     789
2010.0     788
2007.0     770
2006.0     763
2009.0     761
2005.0     751
2004.0     740
2003.0     736
2002.0     710
2001.0     694
Name: year, dtype: int64

In [23]:
plants_2010_whatever = pd.read_csv(plants_2010)
plants_2010_whatever['Fuel Types'].unique()

array(['NG', 'KER,NG', 'KER', 'WND', 'WAT', 'NG,BIT', 'NG,DFO', 'NG,OG',
       'LFG', 'BIT,DFO', 'NG,PC', 'BIT,DFO,WO,OTH', 'DFO,BIT', 'SUB',
       'DFO', 'SUN', 'NG,AB', 'NG,DFO,SUN', 'GEO', 'WDS,NG,BLQ,DFO', 'JF',
       'NG,OBG', 'NG,DFO,SUB', 'OG', 'BIT,DFO,SUB',
       'NG,OBL,BIT,SUB,PC,OTH', 'WDS,NG,BIT', 'BIT', 'NG,BIT,SUB',
       'DFO,WO,LFG', 'DFO,SUB,OBS', 'WDS', 'NG,DFO,RFO',
       'SLW,WDS,BLQ,WO,RFO', 'NG,WDS,BIT,OBG', 'WAT,RFO', 'LIG,DFO',
       'NG,SUB', 'BFG,NG,OG', 'BFG,NG', 'NG,LFG,OG', 'SLW,NG,BIT,SUB',
       'NG,WDS,BIT,SUB,TDF', 'WAT,DFO', 'NUC', 'BIT,DFO,SUB,TDF,PC',
       'NG,PG', 'WDS,NG,BIT,BLQ,TDF,RFO', 'NG,DFO,BIT', 'NG,RFO',
       'BIT,OG', 'DFO,BIT,SUB,RFO', 'WH', 'DFO,SUB', 'NG,MSN,MSB',
       'NG,WDS,SUB,TDF', 'NG,DFO,SUN,OG', 'OTH', 'OBS', 'LIG,NG,SUB',
       'OBG', 'WDS,NG,BIT,SUB', 'WDS,PG', 'SLW,WDS,NG,BLQ', 'WDS,BIT,BLQ',
       'DFO,WO', 'WAT,BIT', 'NG,SUB,PC', 'NG,DFO,BIT,RFO',
       'DFO,JF,SUB,RFO', 'WDS,DFO', 'WO,LFG', 'WDS,NG,BLQ,DFO,RFO,TDF',
       'DFO,LFG', 'NG,WDS,DFO,BIT', 'WDS,NG,BLQ',
       'SLW,NG,WDS,BIT,DFO,TDF,RFO', 'RFO', 'NG,WDS', 'NG,BIT,DFO,RFO',
       'NG,BIT,DFO', 'PC', 'NG,BIT,DFO,SUB', 'WDS,BIT,TDF', 'BIT,OBS,TDF',
       'MSN,MSB', 'WAT,NG,RFO', 'WC', 'DFO,OBL', 'WDS,BIT,BLQ,RFO',
       'WAT,DFO,RFO', 'WND,OTH', 'WDS,BIT,DFO', 'DFO,BIT,SUB',
       'BIT,WC,PC', 'NG,BLQ,DFO', 'DFO,AB', 'DFO,WO,SUB', 'WC,DFO',
       'NG,BIT,DFO,LFG', 'NG,BIT,DFO,PC,OTH', 'MSN,DFO,MSB',
       'WDS,NG,MSN,MSB', 'WDS,MSN,DFO,MSB', 'WDS,NG,BIT,DFO,BLQ,RFO',
       'WDS,OBS', 'BIT,DFO,PC', 'BIT,DFO,NUC', 'NG,DFO,BIT,SUB,RFO',
       'WDS,NG,BLQ,TDF', 'SLW,WDS,NG,BIT', 'WND,WAT,DFO,OBG,SUN',
       'NG,WDS,TDF,PC', 'LIG,NG', 'NG,OTH', 'SLW,WDS,NG,BLQ,DFO,TDF',
       'WDS,BIT,DFO,BLQ,RFO', 'WAT,WDS,NG', 'NG,DFO,BIT,SUB', 'PUR',
       'NG,JF', 'NG,DFO,PC', 'DFO,RFO', 'NG,BIT,DFO,LFG,RFO',
       'DFO,SUB,TDF', 'NG,MSN,DFO,MSB,TDF', 'DFO,OBG', 'NG,BIT,PG',
       'NG,BIT,DFO,PG,TDF,PC', 'AB', 'DFO,BIT,PC', 'NG,BIT,WC,OG',
       'SLW,WDS,NG,BIT,BLQ,TDF,RFO', 'KER,NG,DFO,RFO', 'NG,WDS,DFO',
       'BFG', 'OTH,OG', 'NG,LFG', 'DFO,NUC', 'WDS,BLQ,BIT,RFO',
       'WDS,DFO,OBS,TDF,RFO', 'NG,WDS,WDL,RFO', 'DFO,SUB,PC',
       'NG,SUB,TDF', 'WDS,BIT,OBS', 'WDS,BLQ,DFO,RFO',
       'WDS,NG,BIT,BLQ,RFO', 'NG,WC', 'NG,OBS', 'NG,DFO,PUR,RFO',
       'WDS,NG,MSN,DFO,MSB', 'NG,BIT,AB', 'BFG,NG,RFO,OG', 'WAT,OBG',
       'WDS,NG,BLQ,RFO', 'WND,NG,DFO', 'NG,TDF',
       'WAT,WDS,NG,DFO,BLQ,BIT,OTH', 'SLW,NG,DFO,RFO,OTH',
       'WDS,NG,BIT,RFO', 'WAT,WDS,NG,BLQ,BIT', 'NG,WDS,BLQ,WO,TDF',
       'WDS,NG,BLQ,PC', 'NG,WO', 'BFG,NG,PUR', 'WDS,NG,TDF',
       'NG,BIT,DFO,NUC', 'DFO,BIT,AB', 'BIT,DFO,AB', 'NG,DFO,SUB,RFO',
       'WO,OG', 'WDS,BIT,DFO,OBL,WO,OBS', 'DFO,WC', 'WDS,SUB',
       'NG,WDS,TDF', 'WAT,DFO,SUB', 'BIT,WC,DFO', 'NG,BLQ,DFO,RFO',
       'WDS,BIT', 'NG,WDS,BIT,DFO,BLQ,OTH,RFO', 'NG,BLQ,RFO',
       'SLW,WDS,NG,BLQ,TDF,RFO', 'WDS,BIT,DFO,BLQ,WO,TDF',
       'NG,WDS,BLQ,BIT,RFO', 'WDS,NG,BIT,BLQ,DFO,TDF,RFO',
       'WDS,NG,BIT,BLQ', 'WDS,NG,BIT,BLQ,WO', 'SLW,WDS,NG,BLQ,BIT,RFO',
       'NG,WDS,DFO,BLQ', 'NG,BLQ,OBS,RFO', 'NG,BLQ,OBS,RFO,PC',
       'WDS,NG,BLQ,TDF,AB', 'WDS,NG,BLQ,DFO,TDF,RFO', 'NG,WDS,BIT,OBS',
       'BIT,SUB', 'WAT,DFO,BIT,WO,RFO', 'WDS,TDF', 'NG,BIT,DFO,BLQ',
       'WAT,NG,DFO', 'BIT,RFO', 'DFO,OTH',
       'WDS,NG,BIT,BLQ,DFO,TDF,RFO,PC', 'NG,BIT,WH', 'WDS,NG,AB',
       'WND,DFO', 'NG,OTH,OG', 'NG,DFO,BIT,SUB,TDF', 'WND,NG,SUB',
       'MSN,MSB,PG', 'WDS,NG,BLQ,PG', 'MSN,MSB,WO', 'LIG,DFO,SUB',
       'SLW,WDS,BLQ', 'NG,DFO,WO', 'WDS,NG,BLQ,WO', 'NG,BIT,BLQ,DFO,WO',
       'NG,WDS,SUB', 'NG,DFO,BIT,TDF', 'WDS,NG,DFO,BIT,SUB,PC',
       'NG,WDS,BLQ,TDF,RFO', 'NG,WC,DFO,BIT', 'WDS,BLQ', 'NG,WDS,BLQ',
       'NG,BIT,DFO,SUB,RFO', 'DFO,BIT,JF', 'KER,NG,RFO', 'WAT,NG',
       'BIT,WC', 'WAT,SLW,WDS,NG,BLQ,BIT,DFO,RFO', 'WDS,BIT,PC',
       'DFO,BIT,JF,WO', 'NG,SUN', 'SLW,WDS,NG,BLQ,DFO,SUB,RFO',
       'DFO,JF,RFO', 'WDS,WC,WO,TDF', 'NG,DFO,BIT,PC,RFO', 'NG,WDS,OTH',
       'BIT,WO', 'WDS,NG,DFO,AB', 'NG,WDS,OBL', 'KER,NG,BIT',
       'NG,DFO,BLQ', 'WAT,WDS,NG,OBG,BLQ,BIT,OBS,RFO', 'NG,DFO,OG',
       'NG,WO,RFO,OG', 'WAT,DFO,JF', 'RFO,OG', 'WDS,LFG',
       'WDS,DFO,WC,OTH', 'WDS,NG,BIT,DFO,BLQ,TDF',
       'SLW,WDS,BIT,BLQ,DFO,RFO', 'WAT,SLW,WDS,BLQ,WO',
       'SLW,WDS,NG,BLQ,DFO', 'WO,PG,TDF', 'NG,DFO,SUB,PC',
       'BFG,NG,WO,RFO', 'WAT,WDS,NG,SUB', 'BIT,DFO,JF,TDF,PC',
       'LIG,WDS,NG', 'NG,MSN,WDS,MSB', 'NG,DFO,OBG,OTH',
       'WAT,NG,DFO,BIT,OTH', 'BIT,PC', 'BIT,PG,PC', 'KER,NG,DFO',
       'SLW,WDS,NG,BIT,OBL,BLQ', 'SLW,NG,WDS', 'SLW,WDS,BIT,BLQ,TDF,RFO',
       'WAT,WDS,DFO,BIT,RFO', 'NG,DFO,OBG,LFG', 'BIT,DFO,RFO',
       'WAT,SLW,WDS,NG,DFO,BLQ', 'WAT,SLW,WDS,BIT,TDF',
       'NG,WDS,BIT,DFO,PC', 'WDS,NG,BIT,JF,OBS,RFO', 'NG,PC,OTH',
       'BIT,SUB,PG,TDF,AB', 'SLW,WDS,BLQ,DFO,OBL,TDF,RFO', 'JF,RFO',
       'NG,SUB,RFO', 'DFO,SUN,SUB', 'BIT,TDF', 'NG,BIT,PC,TDF,AB',
       'NG,OBG,LFG', 'WDS,BIT,SUB,TDF,PC', 'SLW,NG,BIT,OTH,OG', 'DFO,JF',
       'NG,PUR', 'WDS,BLQ,RFO', 'WAT,WDS,DFO,RFO', 'NG,WH', 'WAT,JF',
       'NG,DFO,RFO,NUC', 'BIT,BLQ', 'NG,WDS,BIT,TDF', 'NG,BIT,OTH',
       'NG,DFO,BIT,OBS', 'NG,BIT,DFO,PC', 'NG,PC,OG', 'NG,DFO,BIT,SUB,PG',
       'WDS,NG,BLQ,BIT', 'NG,SUB,OBS', 'WDS,NG,DFO,BIT', 'NG,WO,OG',
       'NG,BIT,DFO,BLQ,OTH', 'NG,BIT,DFO,OBS,TDF',
       'SLW,WDS,BIT,DFO,BLQ,OBS,RFO', 'WDS,LFG,TDF', 'BIT,DFO,WO',
       'WDS,NG,BLQ,SUB', 'WAT,WDS,BLQ,RFO', 'NG,DFO,OBG',
       'NG,BIT,DFO,SUB,TDF', 'DFO,PC,OG'], dtype=object)